/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import UserInterface.SystemAdminWorkArea.ManageEnterpriseJPanel;
import java.util.ArrayList;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author puja_
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {
    
     JPanel userProcessContainer;
     Business business;

    /**
     * Creates new form SystemAdminWorkAreaPanel
     */
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,Business business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
         populateTree();
    }
    
   public void populateTree(){
        DefaultTreeModel model=(DefaultTreeModel)jTree1.getModel();
        ArrayList<Network> networkList=business.getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        
        Network network;
        Enterprise enterprise;
        Organization organization;
        
        DefaultMutableTreeNode networks=new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);
        
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        
        for(int i=0;i<networkList.size();i++){
            network=networkList.get(i);
            networkNode=new DefaultMutableTreeNode(network.getName());
            networks.insert(networkNode, i);
            
            enterpriseList=network.getEnterpriseDirectory().getEnterpriseList();
            for(int j=0; j<enterpriseList.size();j++){
                enterprise=enterpriseList.get(j);
                enterpriseNode=new DefaultMutableTreeNode(enterprise.getName());
                networkNode.insert(enterpriseNode, j);
                
                organizationList=enterprise.getOrganizationDirectory().getOrganizationList();
                for(int k=0;k<organizationList.size();k++){
                    organization=organizationList.get(k);
                    organizationNode=new DefaultMutableTreeNode(organization.getName());
                    enterpriseNode.insert(organizationNode, k);
                }
            }
        }
        model.reload();
    }

   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel4 = new javax.swing.JPanel();
        selectednodeLbl = new javax.swing.JLabel();
        manageentBtn = new javax.swing.JButton();
        manageentadminBtn = new javax.swing.JButton();
        btnManageNetwork = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane2.setBackground(new java.awt.Color(0, 204, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 334, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        selectednodeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/Webp.net-resizeimage (1)_burned.png"))); // NOI18N
        jPanel4.add(selectednodeLbl);
        selectednodeLbl.setBounds(500, 10, 440, 179);

        manageentBtn.setBackground(new java.awt.Color(4, 126, 187));
        manageentBtn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        manageentBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageentBtn.setText("Manage Enterprise");
        manageentBtn.setMaximumSize(new java.awt.Dimension(229, 29));
        manageentBtn.setMinimumSize(new java.awt.Dimension(229, 29));
        manageentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageentBtnActionPerformed(evt);
            }
        });
        jPanel4.add(manageentBtn);
        manageentBtn.setBounds(50, 440, 230, 50);

        manageentadminBtn.setBackground(new java.awt.Color(4, 126, 187));
        manageentadminBtn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        manageentadminBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageentadminBtn.setText("Manage Enterprise Admin");
        manageentadminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageentadminBtnActionPerformed(evt);
            }
        });
        jPanel4.add(manageentadminBtn);
        manageentadminBtn.setBounds(370, 440, 230, 50);

        btnManageNetwork.setBackground(new java.awt.Color(4, 126, 187));
        btnManageNetwork.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnManageNetwork.setForeground(new java.awt.Color(255, 255, 255));
        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.setMaximumSize(new java.awt.Dimension(229, 29));
        btnManageNetwork.setMinimumSize(new java.awt.Dimension(229, 29));
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });
        jPanel4.add(btnManageNetwork);
        btnManageNetwork.setBounds(690, 440, 230, 50);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECT NODE: <VIEW SELECTED NODE>", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 153, 204))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(10, 220, 920, 290);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/Webp.png"))); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(70, 270, 180, 144);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/Webp.net-resizeimage (11).png"))); // NOI18N
        jPanel4.add(jLabel3);
        jLabel3.setBounds(420, 270, 143, 143);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/Webp.net-resizeimage (5).png"))); // NOI18N
        jPanel4.add(jLabel4);
        jLabel4.setBounds(720, 260, 164, 164);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/healthcare-and-medical-background-with-hexagonal-geometric-shapes_1017-11948 (1).jpg"))); // NOI18N
        jPanel4.add(jLabel5);
        jLabel5.setBounds(0, 0, 950, 590);

        jSplitPane2.setRightComponent(jPanel4);

        add(jSplitPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageentBtnActionPerformed
ManageEnterpriseJPanel manageEnterpriseJPanel=new ManageEnterpriseJPanel(userProcessContainer, business);
        userProcessContainer.add("manageEnterpriseJPanel",manageEnterpriseJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
        
    }//GEN-LAST:event_manageentBtnActionPerformed

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        ManageNetworkJPanel manageNetworkJPanel=new ManageNetworkJPanel(userProcessContainer, business);
        userProcessContainer.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void manageentadminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageentadminBtnActionPerformed
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel=new ManageEnterpriseAdminJPanel(userProcessContainer, business);
        userProcessContainer.add("manageEnterpriseAdminJPanel",manageEnterpriseAdminJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_manageentadminBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton manageentBtn;
    private javax.swing.JButton manageentadminBtn;
    private javax.swing.JLabel selectednodeLbl;
    // End of variables declaration//GEN-END:variables
}
