

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BloodReceptionWorkAreaJPanel;

import Business.Business;
import Business.Organisation.BloodbankReceptionOrganization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organisation.DoctorOrganization;
import Business.Organisation.Organization;
import Business.RequestBloodWorkQueue.RequestBloodFromDoctorWorkRequest;
import Business.RequestBloodWorkQueue.RequestBloodWorkRequest;
import Business.WorkQueue.GetBloodFromCollectionWorkRequest;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author puja_
 */
public class BloodReceptionWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private BloodbankReceptionOrganization bloodbankReceptionOrganization;
    private UserAccount account;
    private Enterprise enterprise;
    //private getBloodFromCollectionWorkRequest request;
    private Organization organization;

    private GetBloodFromCollectionWorkRequest bloodrequest;
    private Business business;
    


    /**
     * Creates new form ReceptionWorkAreaJPanel
     */
    public BloodReceptionWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Business business) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.bloodbankReceptionOrganization= (BloodbankReceptionOrganization)organization;
        this.account=account;

        this.organization = organization;

        this.enterprise = enterprise;
        this.business = business;
        populateTable();
        populateCollectionRequest();
    }
    
    public void populateTable()
    {
        

        DefaultTableModel model2 = (DefaultTableModel) BloodRequestJTable.getModel();

        model2.setRowCount(0);
        for(RequestBloodWorkRequest rbwr :bloodbankReceptionOrganization.getReceiverRequestFromDoctor().getWorkRequestList())
        {
            
            Object[] row = new Object[5];
            row[0] = rbwr;
            row[1] = rbwr.getBloodType();
            row[2] = rbwr.getQty();
            row[3] = rbwr.getStatus();
            row[4] = rbwr.getSender();
            model2.addRow(row);
        }
    }
    
    public void populateCollectionRequest()
    {
        DefaultTableModel model1 = (DefaultTableModel) RequestRaisedforCollection.getModel();

        model1.setRowCount(0);
        
        for(Organization organization :enterprise.getOrganizationDirectory().getOrganizationList())
            if(organization instanceof BloodbankReceptionOrganization)
            {
                for(RequestBloodWorkRequest gbfc :organization.getReceiverRequestFromDoctor().getWorkRequestList())
        {
            if(gbfc.getStatus().equals("Sent from col to rep"))
            {
            Object[] row = new Object[6];
            row[0] = gbfc;
            row[1] = gbfc.getBloodType();
            row[2] = gbfc.getQty();
            row[3] = gbfc.getSender();
            gbfc.setReceiver(account);
            row[4] = gbfc.getReceiver();
            row[5] = gbfc.getStatus();
            
            model1.addRow(row);
            }
        }
            }
     
       
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BloodRequestJTable = new javax.swing.JTable();
        sendrequestBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        valueLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RequestRaisedforCollection = new javax.swing.JTable();
        sendToDoctor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(222, 248, 248));
        setLayout(null);

        BloodRequestJTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        BloodRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Blood Type", "Quantity Needed", "Status for Doctor", "Sender"
            }
        ));
        jScrollPane1.setViewportView(BloodRequestJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(6, 98, 1002, 96);

        sendrequestBtn.setBackground(new java.awt.Color(0, 153, 153));
        sendrequestBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendrequestBtn.setText("Send Blood Request to collection");
        sendrequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendrequestBtnActionPerformed(evt);
            }
        });
        add(sendrequestBtn);
        sendrequestBtn.setBounds(740, 210, 249, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Enterprise:");
        add(jLabel1);
        jLabel1.setBounds(160, 40, 98, 22);

        valueLbl.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        valueLbl.setText("<value>");
        add(valueLbl);
        valueLbl.setBounds(380, 50, 45, 15);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Request Received from Doctor");
        add(jLabel2);
        jLabel2.setBounds(130, 70, 310, 30);

        RequestRaisedforCollection.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Blood Type", "Quantity", "Sender", "Receiver", "Status"
            }
        ));
        jScrollPane2.setViewportView(RequestRaisedforCollection);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 330, 788, 95);

        sendToDoctor.setBackground(new java.awt.Color(0, 153, 153));
        sendToDoctor.setForeground(new java.awt.Color(255, 255, 255));
        sendToDoctor.setText("Send to Doctor");
        sendToDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendToDoctorActionPerformed(evt);
            }
        });
        add(sendToDoctor);
        sendToDoctor.setBounds(570, 440, 226, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Request Raised for collection Organization");
        add(jLabel3);
        jLabel3.setBounds(270, 280, 420, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void sendrequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendrequestBtnActionPerformed


        

        int selectedRow = BloodRequestJTable.getSelectedRow();
if(selectedRow < 0)
{
    JOptionPane.showMessageDialog(null,"No Request Selected");
    return;
}
RequestBloodWorkRequest rbwr = (RequestBloodFromDoctorWorkRequest)BloodRequestJTable.getModel().getValueAt(selectedRow, 0);
rbwr.setStatus("Sent to Blood Collection");
    populateCollectionRequest();
    JOptionPane.showMessageDialog(null,"request sent to collection");



    }//GEN-LAST:event_sendrequestBtnActionPerformed

    private void sendToDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToDoctorActionPerformed
        
int selectedRow = RequestRaisedforCollection.getSelectedRow();
if(selectedRow < 0)
{
    JOptionPane.showMessageDialog(null,"No Request Selected");
    return;
}
RequestBloodFromDoctorWorkRequest workRequest = (RequestBloodFromDoctorWorkRequest)RequestRaisedforCollection.getModel().getValueAt(selectedRow, 0);
for(Network network: business.getNetworkList() )
{
   for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList())
   {
       if(enterprise instanceof HospitalEnterprise)
       {
           for(Organization organization: enterprise.getOrganizationDirectory().getOrganizationList())
           {
               if(organization instanceof DoctorOrganization)
               {
                    
        workRequest.setSender(account);
        workRequest.setStatus("Blood received by doctor");
        workRequest.getGdwr().setStatus("Blood received by doctor");
               }
           }
       }
   }
}
DefaultTableModel model1 = (DefaultTableModel) RequestRaisedforCollection.getModel();
model1.removeRow(selectedRow);
    
       
        



// TODO add your handling code here:
    }//GEN-LAST:event_sendToDoctorActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BloodRequestJTable;
    private javax.swing.JTable RequestRaisedforCollection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sendToDoctor;
    private javax.swing.JButton sendrequestBtn;
    private javax.swing.JLabel valueLbl;
    // End of variables declaration//GEN-END:variables
}

