/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BloodReceptionWorkAreaJPanel;

import Business.Camp.Camp;
import Business.Enterprise.Enterprise;
import Business.Organisation.Organization;
import Business.UserAccount.UserAccount;

import Business.WorkQueue.GetBloodFromCollectionWorkRequest;

import UserInterface.ReceptionWorkAreaJpanel.ReceptionWorkareaJpanel;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author puja_
 */
public class BloodCampJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private Organization organization;
    private final List<Camp> collection;


    /**
     * Creates new form BloodCampJPanel
     */
    public BloodCampJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, List<Camp> collection) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.collection = collection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valueLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campareaTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bloodtypeCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        quantityTxt = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        BankBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(222, 248, 248));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enterprise:");
        add(jLabel1);
        jLabel1.setBounds(280, 80, 100, 22);

        valueLbl.setText("<value>");
        add(valueLbl);
        valueLbl.setBounds(460, 90, 53, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Camp Area:");
        add(jLabel2);
        jLabel2.setBounds(276, 140, 71, 17);
        add(campareaTxt);
        campareaTxt.setBounds(421, 135, 166, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Blood Type Collected:");
        add(jLabel3);
        jLabel3.setBounds(214, 202, 133, 17);

        bloodtypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+ve", "B+ve", "O+ve", "AB-ve", "AB+ve", "A-ve", "B-ve" }));
        bloodtypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodtypeComboActionPerformed(evt);
            }
        });
        add(bloodtypeCombo);
        bloodtypeCombo.setBounds(421, 192, 166, 27);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Quantity Collected:");
        add(jLabel4);
        jLabel4.setBounds(230, 262, 117, 17);

        quantityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTxtActionPerformed(evt);
            }
        });
        add(quantityTxt);
        quantityTxt.setBounds(421, 257, 166, 28);

        submitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/submit.png"))); // NOI18N
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn);
        submitBtn.setBounds(510, 330, 140, 50);

        BankBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/back.png"))); // NOI18N
        BankBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankBtnActionPerformed(evt);
            }
        });
        add(BankBtn);
        BankBtn.setBounds(190, 330, 140, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void quantityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTxtActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:


        int quantity = Integer.parseInt(quantityTxt.getText());

        String bloodType = (String) bloodtypeCombo.getSelectedItem();

         boolean flag = true;

        
       if(!this.collection.isEmpty())
       {
           
           
           for (Camp camp1 : this.collection) {
            
            if (camp1.getBloodType().equals(bloodType)) {
                camp1.setQuantity(camp1.getQuantity() + quantity);
                flag = false;
                break;
               // this.collection.add(camp);
               
            }
           }
           
                if(flag)
                {
                Camp camp = new Camp();
                camp.setBloodType(bloodType);
                camp.setQuantity(quantity);
                this.collection.add(camp);
                }
             
            }
      
       else
       {
                Camp camp = new Camp();
                camp.setBloodType(bloodType);
                camp.setQuantity(quantity);
                this.collection.add(camp);
       }
        
        JOptionPane.showMessageDialog(null, "Camp recorded successfully");      


    }//GEN-LAST:event_submitBtnActionPerformed

    private void bloodtypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodtypeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodtypeComboActionPerformed

    private void BankBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankBtnActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        BloodCollectionWorkAreaJPanel rwajp = (BloodCollectionWorkAreaJPanel) component;
        rwajp.populateBloodbankInventoryTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_BankBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BankBtn;
    private javax.swing.JComboBox bloodtypeCombo;
    private javax.swing.JTextField campareaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel valueLbl;
    // End of variables declaration//GEN-END:variables
}
