/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LabWorkAreaPanel;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.LabWorkQueueArea.RequestLabWorkAreaRequest;
import Business.LabWorkQueueArea.RequestLabWorkRequest;
import Business.Organisation.LabAssistantOrganization;
import Business.Organisation.LabReceptionOrganization;
import Business.Organisation.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author puja_
 */
public class LabAssistantWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private Business business;
    private Organization organization;
    private LabAssistantOrganization labAssistantOrganization;
    
    public LabAssistantWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Business business, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.account= account;
        this.business = business;
        this.organization = organization;
        this.enterprise = enterprise;
        this.labAssistantOrganization = (LabAssistantOrganization)organization;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)labassistantJTable.getModel();
        model.setRowCount(0);
        
        for(Organization organization :enterprise.getOrganizationDirectory().getOrganizationList())
            if(organization instanceof LabReceptionOrganization)
            {
                for(RequestLabWorkAreaRequest request : organization.getReceiveLabRequest().getLabWorkRequestList()){
                    Object[] row = new Object[6];
                    row[0] = request;
                    row[1] = request.getTestType();
                    row[2] = request.getSender();
                    request.setReceiver(account);
                    row[3] = request.getReceiver();
                    row[4] = request.getStatus();
                    row[5] = request.getResult();
                    model.addRow(row);
                }
            }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labassistantJTable = new javax.swing.JTable();
        assigntomeBtn = new javax.swing.JButton();
        sendresultBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(222, 248, 248));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Lab Assistant Work Area");

        labassistantJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Test Type", "Sender", "Receiver", "Status", "Result"
            }
        ));
        jScrollPane1.setViewportView(labassistantJTable);

        assigntomeBtn.setBackground(new java.awt.Color(0, 153, 153));
        assigntomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        assigntomeBtn.setText("Assign to Me");
        assigntomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assigntomeBtnActionPerformed(evt);
            }
        });

        sendresultBtn.setBackground(new java.awt.Color(0, 153, 153));
        sendresultBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendresultBtn.setText("Send Result");
        sendresultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendresultBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(248, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(assigntomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sendresultBtn)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(93, 93, 93)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assigntomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendresultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(289, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assigntomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assigntomeBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = labassistantJTable.getSelectedRow();
if(selectedRow < 0)
{
    return;
}

RequestLabWorkAreaRequest workRequest = (RequestLabWorkAreaRequest)labassistantJTable.getValueAt(selectedRow, 0);
workRequest.setReceiver(account);
workRequest.setStatus("pending");
populateTable();
    }//GEN-LAST:event_assigntomeBtnActionPerformed

    private void sendresultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendresultBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = labassistantJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        RequestLabWorkRequest request = (RequestLabWorkRequest)labassistantJTable.getValueAt(selectedRow, 0);
        
        
        ResultJPanel  result = new ResultJPanel(userProcessContainer, request);
        userProcessContainer.add("diagnosis", result);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_sendresultBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assigntomeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable labassistantJTable;
    private javax.swing.JButton sendresultBtn;
    // End of variables declaration//GEN-END:variables
}
