/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorWorkAreaPanel;

import Business.DoctorWorkQueue.GetDoctorWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;

import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;

//import java.net.PasswordAuthentication;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author Mrunal
 */
public class Diagnosis extends javax.swing.JPanel {

    /**
     * Creates new form Diagnosis
     */
    JPanel userProcessContainer;
    GetDoctorWorkRequest request;
    public Diagnosis(JPanel userProcessContainer, GetDoctorWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        
        patientName.setText(request.getPatientName());
        patientAge.setText(String.valueOf(request.getPatientAge()));
        diagnosisTxtField.setText(request.getDiagnosis());
        CaseType.setText(request.getCastType());
        GenderType.setText(request.getPatientGender());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sendDiagnosis = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        diagnosisTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        patientName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        patientAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CaseType = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        GenderType = new javax.swing.JTextField();

        setBackground(new java.awt.Color(222, 248, 248));
        setLayout(null);

        jLabel1.setText("Diagnosis : ");
        add(jLabel1);
        jLabel1.setBounds(51, 140, 77, 29);

        sendDiagnosis.setBackground(new java.awt.Color(0, 102, 153));
        sendDiagnosis.setForeground(new java.awt.Color(255, 255, 255));
        sendDiagnosis.setText("Send Diagnosis");
        sendDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendDiagnosisActionPerformed(evt);
            }
        });
        add(sendDiagnosis);
        sendDiagnosis.setBounds(220, 292, 150, 40);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/Webp.net-resizeimage (9).png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(22, 305, 62, 29);
        add(diagnosisTxtField);
        diagnosisTxtField.setBounds(144, 140, 197, 29);

        jLabel2.setText("Patient Name:");
        add(jLabel2);
        jLabel2.setBounds(51, 60, 87, 16);
        add(patientName);
        patientName.setBounds(144, 54, 197, 28);

        jLabel3.setText("Patient Age:");
        add(jLabel3);
        jLabel3.setBounds(51, 106, 75, 16);
        add(patientAge);
        patientAge.setBounds(144, 100, 197, 28);

        jLabel4.setText("Case Type:");
        add(jLabel4);
        jLabel4.setBounds(51, 193, 68, 16);
        add(CaseType);
        CaseType.setBounds(144, 187, 197, 29);

        jLabel5.setText("Gender Type:");
        add(jLabel5);
        jLabel5.setBounds(51, 240, 82, 16);
        add(GenderType);
        GenderType.setBounds(145, 234, 196, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void sendDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendDiagnosisActionPerformed
       String host="smtp.gmail.com";
  final String user="sailee491994@gmail.com";//change accordingly
  final String password="itachi@1404";//change accordingly
  
  String to="sailee491994@gmail.com";//change accordingly

   //Get the session object
   Properties props = new Properties();
   //props.put("mail.smtp.host",host);
   //props.put("mail.smtp.auth", "true");
   props.setProperty("mail.transport.protocol", "smtp");     
    props.setProperty("mail.host", "smtp.gmail.com");  
    props.put("mail.smtp.auth", "true");  
    props.put("mail.smtp.port", "465");  
    props.put("mail.debug", "true");  
    props.put("mail.smtp.socketFactory.port", "465");  
    props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");  
    props.put("mail.smtp.socketFactory.fallback", "false");  
   
   Session session = Session.getDefaultInstance(props,
    new javax.mail.Authenticator() {
      protected PasswordAuthentication getPasswordAuthentication() {
	return new PasswordAuthentication(user,password);
      }
    });

   //Compose the message
    try {
     MimeMessage message = new MimeMessage(session);
     message.setFrom(new InternetAddress(user));
     message.addRecipient(Message.RecipientType.TO,new InternetAddress(to));
     message.setSubject("Diagnosis Report");
     String Dia = diagnosisTxtField.getText();
     String PatientName = patientName.getText();
     String PatientAge = patientAge.getText();
     String caseType = CaseType.getText();
     String gender = GenderType.getText();
     
     
     message.setText("Patient Name:" +PatientName+ "\nPatient Age:"  +PatientAge+ "\nDiagnosis:" +Dia+ "\nCase type:" +caseType+ "\nGender Type:" +gender);
     
     
    

    
         // Send message
         Transport.send(message);
         System.out.println("Sent message successfully....");
         request.setDiagnosis(diagnosisTxtField.getText());
        request.setStatus("Completed");

        } 
      catch (MessagingException mex) {
         mex.printStackTrace();
        }

        JOptionPane.showMessageDialog(null, "Diagnosis sent successfully");
        




        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_sendDiagnosisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CaseType;
    private javax.swing.JTextField GenderType;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField diagnosisTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField patientAge;
    private javax.swing.JTextField patientName;
    private javax.swing.JButton sendDiagnosis;
    // End of variables declaration//GEN-END:variables
}
