/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorWorkAreaPanel;

import Business.Business;
import Business.DoctorWorkQueue.GetDoctorWorkRequest;
import Business.Enterprise.Enterprise;
import Business.Enterprise.OrganInventoryEnterprise;
import Business.Network.Network;
import Business.Organisation.OrganInventoryReceptionOrganization;
import Business.Organisation.Organization;
import Business.RequestOrganByDoctorWorkArea.RequestOrganFromDoctorWorkRequest;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author puja_
 */
public class ProcessingOrganRequestByDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessingOrganRequestByDoctorJPanel
     */
    private JPanel userProcessContainer;
    private GetDoctorWorkRequest request;
    private UserAccount account;
    private Business business;
    public ProcessingOrganRequestByDoctorJPanel(JPanel userProcessContainer, UserAccount account, GetDoctorWorkRequest request, Business business) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.account = account;
        this.request = request;
        this.business = business;
        populateTable();
    }

    void populateTable()
    {
          DefaultTableModel model = (DefaultTableModel)processOrganRequestJtable.getModel();
        
        model.setRowCount(0);
        
        
            Object[] row = new Object[7];
            row[0] = request;
            row[1] = request.getPatientAge();
            row[2] = request.getPatientGender();
            row[3] = request.getSender();
            request.setReceiver(account);
            row[4] = request.getPatientGender();
            row[5] = request.getCastType();
            row[6] = request.getStatus();
           
            model.addRow(row);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        processOrganRequestJtable = new javax.swing.JTable();
        requestorganBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bloodtypeComboBox = new javax.swing.JComboBox();
        quantityTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        valueLbl = new javax.swing.JLabel();
        organtypeComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(222, 248, 248));

        processOrganRequestJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Patient Age", "Patient Gender", "Doctor(Sender)", "Receiver(Organ Inventory)", "Status"
            }
        ));
        jScrollPane1.setViewportView(processOrganRequestJtable);

        requestorganBtn.setBackground(new java.awt.Color(0, 153, 153));
        requestorganBtn.setForeground(new java.awt.Color(255, 255, 255));
        requestorganBtn.setText("Request Organ");
        requestorganBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestorganBtnActionPerformed(evt);
            }
        });

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ObjectModel/back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Organ Name:");

        jLabel2.setText("Blood Type:");

        jLabel3.setText("Quantity:");

        bloodtypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+ve", "B+ve", "O+ve", "AB+ve", "AB-ve", "O-ve", "B-ve", "A-ve" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Enterprise:");

        valueLbl.setText("<value>");

        organtypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Heart", "Liver", "Kidney", "Lung", "Eye", "Small Bowel", "Pancreas", "Heart Valves", "Skin", "Veins ", "Tendons" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(requestorganBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(405, 405, 405))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(286, 286, 286)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(jLabel4)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valueLbl)
                            .addComponent(bloodtypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quantityTxt)
                            .addComponent(organtypeComboBox, 0, 157, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valueLbl))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(organtypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bloodtypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(requestorganBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestorganBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestorganBtnActionPerformed
        // TODO add your handling code here:
        RequestOrganFromDoctorWorkRequest rofdwr = new RequestOrganFromDoctorWorkRequest();
        rofdwr.setGdwr(request);
        rofdwr.setSender(account);
        rofdwr.setStatus("Request Sent");
        rofdwr.setBloodType((String)bloodtypeComboBox.getSelectedItem());
        rofdwr.setQty(Integer.parseInt(quantityTxt.getText()));
        rofdwr.setOrganType((String)organtypeComboBox.getSelectedItem());
        
                Organization org = null;
for(Network network : business.getNetworkList())
{
    for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList())
    {
        if(enterprise instanceof OrganInventoryEnterprise)
        {
            for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
            {
                if(organization instanceof OrganInventoryReceptionOrganization)
                {
                  
     org = organization;
     break;
                }
            }
        }
    }
}

if(org!=null){
    org.getReceiveOrganRequestFromDoctor().getOrganWorkRequestList().add(rofdwr);
    account.getReceiveOrganRequestFromDoctor().getOrganWorkRequestList().add(rofdwr);
    JOptionPane.showMessageDialog(null,"Request sent to organ reception");
}
    }//GEN-LAST:event_requestorganBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox bloodtypeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organtypeComboBox;
    private javax.swing.JTable processOrganRequestJtable;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton requestorganBtn;
    private javax.swing.JLabel valueLbl;
    // End of variables declaration//GEN-END:variables
}
