/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorWorkAreaPanel;

import Business.Business;
import Business.DoctorWorkQueue.GetDoctorWorkRequest;
import Business.Enterprise.Enterprise;
import Business.Enterprise.LabEnterprise;
import Business.LabWorkQueueArea.RequestLabWorkRequest;
import Business.Network.Network;
import Business.Organisation.LabReceptionOrganization;
import Business.Organisation.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author puja_
 */
public class ProcessingLabRequestByDoctorJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private GetDoctorWorkRequest request;
    private UserAccount account;
    private Business business;

    /**
     * Creates new form ProcessingLabRequestByDoctorJPanel
     */
    public ProcessingLabRequestByDoctorJPanel(JPanel userProcessContainer, UserAccount account, GetDoctorWorkRequest request, Business business) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.account = account;
        this.request = request;
        this.business = business;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        testtypeComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        sendreqBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(222, 248, 248));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Request Lab Tests");

        testtypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blood Type", "Urine Type" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Test Type:");

        sendreqBtn.setBackground(new java.awt.Color(0, 153, 153));
        sendreqBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendreqBtn.setText("Send Request");
        sendreqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendreqBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendreqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(111, 111, 111)
                        .addComponent(testtypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(249, 249, 249))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(testtypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(sendreqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendreqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendreqBtnActionPerformed
        // TODO add your handling code here:
        RequestLabWorkRequest rlwr = new RequestLabWorkRequest();
        rlwr.setGdwr(request);
        rlwr.setSender(account);
        rlwr.setStatus("Request Sent");
        rlwr.setTestType((String)testtypeComboBox.getSelectedItem());
        
         Organization org = null;
for(Network network : business.getNetworkList())
{
    for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList())
    {
        if(enterprise instanceof LabEnterprise)
        {
            for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
            {
                if(organization instanceof LabReceptionOrganization)
                {
                  
     org = organization;
     break;
                }
            }
        }
    }
}
if(org!=null){
    org.getReceiveLabRequest().getLabWorkRequestList().add(rlwr);
    account.getReceiveLabWorkQueue().getLabWorkRequestList().add(rlwr);
}
    }//GEN-LAST:event_sendreqBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton sendreqBtn;
    private javax.swing.JComboBox testtypeComboBox;
    // End of variables declaration//GEN-END:variables
}
